[project]
name = "pmb2pfp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "acdh-cidoc-pyutils>=1.12.1",
    "pyocclient>=0.6",
]
