name: Serialize entity-data to PFP-CIDOC

on:
  workflow_dispatch:

jobs:
  download:
    name: serialize entity-data to PFP-CIDOC
    runs-on: ubuntu-latest
    env:
      OWNCLOUD_USER: ${{ secrets.OWNCLOUD_USER }}
      OWNCLOUD_PW: ${{ secrets.OWNCLOUD_PW }}
      OWNCLOUD_FOLDER: pfp-data
    steps:
      - name: Perform Checkout
        uses: actions/checkout@v6
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7 
      - name: dump the data
        run: ./scripts/build_graph.sh
      - name: validate
        run: ./scripts/validate.sh
      - name: upload artifact if validate fails
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: validation_report
          path: datasets/validation_report.txt